language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover
deploy:
  provider: pypi
  user: "ridi-data"
  password:
    secure: "N/9EpJG3DU99rTkxHo2mmFUUX+Ganm/ccoDIcES0l5f/ZNSVJAtHOYdg3ORQNthOp20eSZQrY5NDSqm9yMCJ0qvPJG0u/5ru13xcKbNqBUEftDpVo3NCSZnRJalPCgmTX9o8gAKKIzRnJK2h8k68N9D4rrAPv7u1w59neF7byA1fyfpYXCqaPakL6jKGS9eMJ/hjYltniembWMzkOI7gbWx41SZKynPt3fmapMP91X7Jx+RWUkeXoDXfCulXLR6cq0TiByEXN6mtw6bP0rqVci8SUUkV/B0blFdi3lB9Ab9g42RromyXxX6iD+9nBx+WXiwxV+IJCcOARLHxAXOGHBkn1Jf9j042NTEm3tj7eSR388wkXopr603LJhrQnfgUmhVHlO1BnP1o8KeL+JZo3nWDaUj7eomdJBXnsdjy6l9VlVD/BDMVBWVyc+x8ceN8/vAux2D4krf0FvAK7iv3d8z+PBNLWWZvBKlV4s2rze7wbc3oDsCgQPvruHBytgmeCHTIdex2qyGgRPiWn/01uOAD6saVoOAxjyzm9Jpok4YYLDfVGfaa/dWw74+Pu3XzifPkpadFmDfGspRllLJa7TLGiIivdT4NNDNYtvsdqMx56RYrpPgx9aEI6Mn5TAWpWjNOh/Yl7Nc2TmkZERnXAHXMmdRxB6FBNak4o/n+8Vs="
