language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover
deploy:
  provider: pypi
  user: "ridi-data"
  password:
    secure: "Y5C+6C+HZBobwy5cs8lizCUyhdz3nnI/fzj+KWS3qjuQzJuQsecCYIQQwRe8VPQIJ0FYAEqGqE9ejYh1ZsvNeW+oNqtTMlX4IXblWGh4qSWcuPV/LeaeIqszukTLoq/IjBHOgrwzdcyegBdSfVTAXT7CR1qKsgnI3WKvOdKWsSDqH08TyTRGHax8m9TScdh+FXMXwhyn0TWBUEBAi/fO3wth2h8MsS96oHSwZUqgPOfQLT7wOnEAcMPHmittW1GBCywYbNoE7pybpRnwlF0ERYa9y8uZbmizqJQ/epkbQLBxU41Qs5FPzeukp8LiYiPIHPQO3x75bNeRGl3eMmO0vlKnzBnMLMpeo4HFWPLXV9fahylwQqiKPO1Yhd9k2MgwnLpopY9w/6GqXDHxFXH95Yfiwg/kvsp7Jw6KUU5m2rgZFrIFECUt/tU0dhl6l6cdCXrvq+GZlzwOqbdsUM/uTH9DpL/QO9bF5YT42ZBtPtPhKDna18+GXdSTKHsF28N9GCJkxFr7L2O6SSkcJSpq2GxMESNFOztBOabXSaodb7Jy32zNQR/gzvkPKjnUsOdclzNHjgKkCLpFHSXiMCJMcNiTeyAHV7jxGApIivNvlo4jQ2irAVsjg+30HtG9V7xkc2t55RcnKlv7x1/J6JW6DsEPafHHW9RZ78aLIYI41Ts="
