language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover
deploy:
  provider: pypi
  user: "ridi-data"
  password:
    secure: "FqHyJDYL7FCJEsW4jckRDq88tq/0mEDzfqmA0RXcjABtw9sRMNM+wMkPu7gZKHqfW2bgztxWyOgr86Is492YB34xQBFY6klFqowTHr3iDLJgkSffMuv8RnAWoB6uc+Zr9R8HkoJmoka7GrI2XIG3jKcpHJpSm9Z0ClbMWKxct7eZnGXCltu2kq5tfEYLX0ehF3Xn6H61KFwcMnyGJzVDvx19QNOeV3IeFO6Tk+y413tpAv9BeZ2M8rBRMgTMGNoCnAVjcD0X92ckutEAyAG0OQTsbzVeIDtUHjKZDOmB5MJMFpzT0Sdehg3Ljx+Tnz0CWIdKTkwr9MO1aCTH7z81w8PGpKyS1uFntl7xHfNm2wSPciSie3PqWXtq2qDRgZ6sMJFOlLlivd9SCgmH6vy/dL0e+SLXHB/rd1DCmogibCUmzbrNJ2g1WBBd+bynXPQpKXb1fykzwLlaNnJwldG6vAhsUHPFCqC0JxA3oUmPjnqp7lGMPeWPFCC/Ik++J3kiret8BDhvVwXAzahC3yoPFJbVBNu+ggQUIUAPYBcZKCpDrJKt2dlvgQ1SPoXm6uRa0ZfzjiZ0k0J3aBLwsJ+JjduPgDcdoyRjwdN5ZuvdpHdeHzV6Ve8ZsFQ6XtrFdAEa79K+5cUFiKSzN/ZJt6W8yI41qgcNiokPCuKNP/UIkOk="
